# List available commands
default:
    just --list --unsorted --list-heading $'Available commands\n'

# Set up dev container. This step runs after building the dev container
post-create: setup-zsh-environment setup-go-environment install-atuin

[private]
setup-go-environment:
    go install github.com/cespare/reflex@latest
    go install github.com/swaggo/swag/cmd/swag@latest

[private]
setup-zsh-environment:
    #!/bin/zsh

    echo "Updating zsh configuration"
    cp -f .zshrc ~/.zshrc

[private]
install-atuin:
    #!/bin/zsh

    echo Y | bash <(curl --proto '=https' --tlsv1.2 -sSf https://setup.atuin.sh)
