services:
  db:
    container_name: davs-db
    restart: always
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: davs_db
      POSTGRES_PASSWORD: secure-password
      POSTGRES_USER: davs-user

  adminer:
    container_name: davs-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
