// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://github.com/kamaal111/davs/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/contacts": {
            "post": {
                "description": "To create a contact",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contacts"
                ],
                "summary": "Create a contact",
                "operationId": "createContact",
                "parameters": [
                    {
                        "description": "Contact information used to create a contact",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contacts.createPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contacts.createResponse"
                        }
                    }
                }
            }
        },
        "/health/ping": {
            "get": {
                "description": "To pings the server",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Checks if server is up or down",
                "operationId": "healthPing",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/healthPing.pingResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "contacts.createPayload": {
            "type": "object",
            "required": [
                "first_name",
                "phones"
            ],
            "properties": {
                "addresses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/contacts.createPayloadAddress"
                    }
                },
                "birthday": {
                    "type": "string",
                    "nullable": true,
                    "example": "1990-10-12"
                },
                "first_name": {
                    "type": "string",
                    "minLength": 1,
                    "example": "Kamaal"
                },
                "last_name": {
                    "type": "string",
                    "minLength": 1,
                    "nullable": true,
                    "example": "Appledoe"
                },
                "nickname": {
                    "type": "string",
                    "minLength": 1,
                    "nullable": true,
                    "example": "K"
                },
                "phones": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/contacts.createPayloadPhone"
                    }
                }
            }
        },
        "contacts.createPayloadAddress": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                },
                "types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "contacts.createPayloadPhone": {
            "type": "object",
            "required": [
                "number"
            ],
            "properties": {
                "number": {
                    "type": "string",
                    "minLength": 5,
                    "example": "+31611111111"
                },
                "types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "VOICE"
                    ]
                }
            }
        },
        "contacts.createResponse": {
            "type": "object"
        },
        "healthPing.pingResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "DAVS API",
	Description:      "API for DAVS",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
