# List available commands
default:
    just --list --unsorted --list-heading $'Available commands\n'

run-dev: build-locales
    #!/bin/zsh

    bun run dev

bootstrap:
    #!/bin/zsh

    curl -fsSL https://bun.sh/install | bash
    just install-modules

build-locales: install-modules
    #!/bin/zsh

    bun run locales:build

typecheck: install-modules
    #!/bin/zsh

    bun run typecheck

[private]
install-modules:
    #!/bin/zsh

    BUN_INSTALL="$HOME/.bun"
    PATH=$BUN_INSTALL/bin:$PATH

    bun i
