# List available commands
default:
    just --list --unsorted --list-heading $'Available commands\n'

run-dev: install-modules
    #!/bin/zsh

    bun run dev

bootstrap:
    #!/bin/zsh

    curl -fsSL https://bun.sh/install | bash
    just install-modules

build-locales: install-modules
    #!/bin/zsh

    bun run locales:build

[private]
install-modules:
    #!/bin/zsh

    bun i
