set dotenv-load

# List available commands
default:
    just --list --unsorted --list-heading $'Available commands\n'

run-dev: install-modules build-locales
    #!/bin/zsh

    export DAVS_SERVER_BASE_URL="http://host.docker.internal:8000"

    pnpm run dev

run: build
    #!/bin/zsh

    export DAVS_SERVER_BASE_URL="http://host.docker.internal:8000"

    pnpm start

build: install-modules build-locales
    pnpm build

test:
    pnpm run test

lint:
    pnpm run lint

format:
    pnpm run format

bootstrap: install-modules build-locales

build-locales:
    pnpm run locales:build

typecheck:
    pnpm run typecheck

[private]
install-modules:
    pnpm i
